---

- hosts: all
  become: true
  tasks:

  - name: update repository index here
    apt:
      update_cache: yes

  - name: install apache2 package
    apt:
      name: apache2 
      state: absent
